default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: minnsec_development 
  adapter: postgresql
  username: minnsec
  password: <%= ENV['minnsec_DATABASE_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: minnsec_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: minnsec_production   
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

