default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['PG_USERNAME'] || 'your_username' %>  # Use env var or a default username
  password: <%= ENV['PG_PASSWORD'] || 'your_password' %>  # Use env var or a default password


development:
  <<: *default
  database: minnsec_development 

test:
  <<: *default
  database: minnsec_test        

production:
  <<: *default
  database: minnsec_production   
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

